server:
  port: 8002

spring:
  application:
    name: locations-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:5001}/eureka
